### ISSUE TITLE
Hi bro

### ISSUE THREAD

**Issue by zycoder142** [Posandu/posandu.github.io#3]
How I can tell you that I like this template, and want to use it for my portfolio

**Comment by Posandu** [comment]
Hey, glad you liked the template!

You can just post a link to this repo or posandu.com in the footer once you use it 🙂

**Comment by zycoder142** [comment]
is it mandatory to include it in the footer?

**Comment by Posandu** [comment]
No, it's fine if you don't. However, a small credit is appreciated though

**Comment by zycoder142** [comment]
![image](https://github.com/Posandu/posandu.github.io/assets/56282560/34a0d5a5-b9cd-4c93-8983-fd6c86b1165a)
I can't clone this repo :(

**Comment by Posandu** [comment]
There's some issue with your internet connection
